server {
    listen 80;

    # 1. Раздача фронтенда (React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html; # Нужно для React Router
    }

    # 2. Проксирование запросов к бэкенду (FastAPI)
    location /zones/ {
        proxy_pass http://backend:8000; # 'backend' — это имя сервиса в docker-compose
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}