[pytest]
pythonpath = src/backend/src
testpaths = src/backend/tests
python_files = test.py tests.py test_*.py *_test.py
xfail_strict = true
filterwarnings = ignore::beartype.roar.BeartypeDecorHintPep585DeprecationWarning